# Generated by Django 6.0.3 on 2026-03-30 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_anuncio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resposta',
            name='pergunta',
        ),
        migrations.DeleteModel(
            name='Pergunta',
        ),
        migrations.DeleteModel(
            name='Resposta',
        ),
    ]
